--SELECT DISTINCT replacement_cost FROM film; 
--SELECT COUNT (DISTINCT replacement_cost ) FROM film;
--SELECT COUNT(*) FROM film WHERE film.title LIKE 'T%' AND film.rating = 'G';
--SELECT COUNT(*) FROM country WHERE length(country.country) = 5;
--SELECT COUNT(*) FROM city WHERE city.city ILIKE '%r';
